spring:
  application:
    name: conta
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ecommerce}
    username: postgres
    password: Postgres2023!

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

server:
  port: 8083

conta:
  servlet:
    path: /conta
  api-key: PIx9BBmbPPLFZfGB

produto:
  api:
    url: ${PRODUTO_API_URL:lb://produto}

# mongo ou inmemory
fabrica:
  repositorios:
    choice: {REPOSITORIOS_CHOICE:bdr}

#logging
logging:
  level:
    org.springframework.web: INFO

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
  endpoint:
    health:
      show-details: always
    circuitbreakers:
      enabled: true
resilience4j.circuitbreaker:
  configs:
    default:
      register-health-indicator: true
