version: '3.9'

services:

  discovery-server:
    container_name: discovery-server
    build: 
      context: ./discovery-server
    ports:
      - "8761:8761"

  postgres-db:
    container_name: postgres-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres2023!
      POSTGRES_DB: ecommerce
    volumes:
      - postgres-db-vol:/var/lib/postgresql/data
  gateway:
    container_name: api-gateway
    build: 
      context: ./gateway
    ports:
      - "8080:8080"
    environment:
      EUREKA_SERVER_URL: http://discovery-server:8761/eureka/
    depends_on:
      - discovery-server

  conta:
    container_name: conta
    build: 
      context: ./conta
    environment:
      DB_URL: jdbc:postgresql://postgres-db:5432/ecommerce
      EUREKA_SERVER_URL: http://discovery-server:8761/eureka/
    depends_on:
      - discovery-server
      - postgres-db

  produto:
    container_name: produto
    build: 
      context: ./produto
    environment:
      DB_URL: jdbc:postgresql://postgres-db:5432/ecommerce
      EUREKA_SERVER_URL: http://discovery-server:8761/eureka/
    depends_on:
      - discovery-server
      - postgres-db

  carrinho:
    container_name: carrinho
    build: 
      context: ./carrinho
    environment:
      DB_URL: jdbc:postgresql://postgres-db:5432/ecommerce
      EUREKA_SERVER_URL: http://discovery-server:8761/eureka/
    depends_on:
      - discovery-server
      - postgres-db

volumes:
  postgres-db-vol: