server:
  port: 8080

urls:
  ecommerce-api:
    uri: http://localhost:8082
  httpbin:
    uri: http://localhost


gateway-paths:
  produto: /produto

spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 30000
        response-timeout: 5s
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: '*'
            allowedHeaders: '*'
      routes:
        - id: user-service
          uri: ${urls.ecommerce-api.uri}
          predicates:
            - Path=${gateway-paths.produto}/**
        - id: httpbin
          uri: ${urls.httpbin.uri}
          predicates:
            - Method=GET,OPTIONS
            - Path=/anything/**

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG
